### ISSUE TITLE
Fix typo error in variable name "huddleCLient" in ReactJS Shinigami Quickstart Documentation

### ISSUE THREAD

**Issue by imsp18** [Huddle01/docs#41]
### Issue Description:
There is a typo error in the documentation located at https://legacy.docs.huddle01.com/docs/React/Shinigami-Quickstart page. The typo pertains to the variable name `huddleClient`.

### Proposed Changes:
To rectify this issue, I suggest correcting the typo in the code snippet provided for integrating the HuddleClient.

#### Details:
In the original code snippet:

```javascript
import { HuddleProvider, HuddleClient } from '@huddle01/react';
 
const huddleCLient = new HuddleClient({ projectId: "YOUR_PROJECT_ID" });
 
...
<HuddleProvider client={huddleCLient}>
  <App />
</HuddleProvider>
...
```

The variable `huddleCLient` should be `huddleClient` instead.

Proposed Modification:

```javascript
import { HuddleProvider, HuddleClient } from '@huddle01/react';
 
const huddleClient = new HuddleClient({ projectId: "YOUR_PROJECT_ID" });
 
...
<HuddleProvider client={huddleClient}>
  <App />
</HuddleProvider>
...
```

This correction ensures consistency and prevents confusion when developers integrate the HuddleClient in their applications.

### Reference:
[Issue - Typo error in variable name huddleCLient in ReactJS Shinigami Quickstart Documentation page](https://legacy.docs.huddle01.com/docs/React/Shinigami-Quickstart)

**Comment by arcinston** [comment]
@imsp18 thanks for pointing it out 🙌
